from __future__ import annotations

import shutil
import time
from dataclasses import dataclass, field
from pathlib import Path

# Everything Pidge writes lives under one folder, so a reset is really just
# "delete some subset of ~/.spidermapp". It's split into targets rather than
# one big wipe because the cost of losing each is wildly different: crawl
# history is regenerated by re-running a crawl, but API keys and OAuth client
# IDs mean going back to four different developer consoles.

BASE_DIR = Path.home() / ".spidermapp"


@dataclass(frozen=True)
class ResetTarget:
    key: str
    label: str
    description: str
    # Paths relative to BASE_DIR. A target can span several files (the
    # credentials one does) so related things are wiped together or not at all.
    relative_paths: tuple[str, ...]
    # Whether this is checked by default in the dialog. Anything expensive to
    # set up again is off by default — a destructive action should never
    # delete more than the user deliberately asked for.
    default_selected: bool = False


TARGETS: tuple[ResetTarget, ...] = (
    ResetTarget(
        key="history",
        label="Historial de crawls",
        description="Todos los rastreos guardados de todos los sitios. Se puede regenerar volviendo a rastrear.",
        relative_paths=("history",),
        default_selected=True,
    ),
    ResetTarget(
        key="checkpoints",
        label="Crawls a medio terminar",
        description="Los puntos de guardado para retomar rastreos pausados o interrumpidos.",
        relative_paths=("checkpoints",),
        default_selected=True,
    ),
    ResetTarget(
        key="tasks",
        label="Tareas del tablero",
        description="Todas las tarjetas del tablero, con sus sub-tareas y comentarios. No se puede recuperar.",
        relative_paths=("tasks.json",),
        default_selected=True,
    ),
    ResetTarget(
        key="brand_visibility",
        label="Análisis de visibilidad de marca",
        description="Los resultados guardados de las mediciones de visibilidad en LLMs.",
        relative_paths=("brand_visibility",),
        default_selected=True,
    ),
    ResetTarget(
        key="settings",
        label="Preferencias",
        description="Vuelve a los valores por defecto: tema, límites de rastreo, URL del servidor.",
        relative_paths=("settings.json",),
        default_selected=False,
    ),
    ResetTarget(
        key="credentials",
        label="Credenciales y sesiones",
        description=(
            "API keys de conectores, client IDs de Google/GitHub/Apple y tu sesión iniciada. "
            "Reconfigurarlas exige volver a cada consola de desarrolladores."
        ),
        relative_paths=("connectors.json", "auth_providers.json", "session.json", "pidge_session.json"),
        default_selected=False,
    ),
)

TARGETS_BY_KEY = {target.key: target for target in TARGETS}


@dataclass
class TargetStatus:
    target: ResetTarget
    exists: bool = False
    item_count: int = 0
    size_bytes: int = 0
    paths: list[Path] = field(default_factory=list)


def _resolve(relative: str, base_dir: Path) -> Path:
    return base_dir / relative


def _dir_size_and_count(path: Path) -> tuple[int, int]:
    total = 0
    count = 0
    for entry in path.rglob("*"):
        if entry.is_file():
            total += entry.stat().st_size
            count += 1
    return total, count


def inventory(base_dir: Path = BASE_DIR) -> list[TargetStatus]:
    """What each target currently holds, so the confirmation dialog can say
    "42 MB en 10 sitios" instead of a vague "se borrarán tus datos"."""
    statuses: list[TargetStatus] = []
    for target in TARGETS:
        status = TargetStatus(target=target)
        for relative in target.relative_paths:
            path = _resolve(relative, base_dir)
            if not path.exists():
                continue
            status.exists = True
            status.paths.append(path)
            if path.is_dir():
                size, _files = _dir_size_and_count(path)
                status.size_bytes += size
                # Count top-level entries (one per site for history), which is
                # the number that means something to a person.
                status.item_count += sum(1 for _ in path.iterdir())
            else:
                status.size_bytes += path.stat().st_size
                status.item_count += 1
        statuses.append(status)
    return statuses


class ResetError(Exception):
    pass


BACKUP_PREFIX = "_respaldo_"


def backup_dir_for(base_dir: Path = BASE_DIR, now: float | None = None) -> Path:
    stamp = time.strftime("%Y%m%d_%H%M%S", time.localtime(now))
    return base_dir / f"{BACKUP_PREFIX}{stamp}"


@dataclass
class ResetReport:
    removed: dict[str, int] = field(default_factory=dict)
    backup_path: Path | None = None

    @property
    def total_files(self) -> int:
        return sum(self.removed.values())


def reset(keys: list[str], base_dir: Path = BASE_DIR, backup: bool = True) -> ResetReport:
    """Clear the selected targets. Returns what was removed and where the
    backup went.

    Backing up is the default and moves the data aside instead of destroying
    it, because most of what this deletes cannot be regenerated — crawl
    history is a record of what a site looked like on a given day, and no
    re-crawl brings back last month's snapshot. With backup=False this is a
    genuine unrecoverable delete: no Trash, no undo.

    Refuses anything that isn't inside base_dir — this walks user-supplied
    keys into filesystem operations, so the containment check is what stops a
    malformed target from ever reaching outside Pidge's own folder.
    """
    unknown = [key for key in keys if key not in TARGETS_BY_KEY]
    if unknown:
        raise ResetError(f"Objetivo de borrado desconocido: {', '.join(unknown)}")

    base_resolved = base_dir.resolve()
    report = ResetReport()

    destination: Path | None = None
    if backup:
        destination = backup_dir_for(base_dir)
        destination.mkdir(parents=True, exist_ok=True)
        report.backup_path = destination

    for key in keys:
        target = TARGETS_BY_KEY[key]
        count = 0
        for relative in target.relative_paths:
            path = _resolve(relative, base_dir)
            if not path.exists():
                continue

            resolved = path.resolve()
            if resolved != base_resolved and base_resolved not in resolved.parents:
                raise ResetError(f"Ruta fuera de {base_dir}: {path}")
            if resolved == base_resolved:
                raise ResetError("Un objetivo no puede ser la carpeta base completa.")
            if resolved.name.startswith(BACKUP_PREFIX):
                raise ResetError("Un respaldo no puede ser objetivo de borrado.")

            files = _dir_size_and_count(path)[1] if path.is_dir() else 1

            if destination is not None:
                shutil.move(str(path), str(destination / path.name))
            elif path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()
            count += files
        report.removed[key] = count

    return report


def list_backups(base_dir: Path = BASE_DIR) -> list[Path]:
    if not base_dir.exists():
        return []
    return sorted(
        (p for p in base_dir.iterdir() if p.is_dir() and p.name.startswith(BACKUP_PREFIX)),
        reverse=True,
    )


def format_size(size_bytes: int) -> str:
    if size_bytes >= 1024 * 1024:
        return f"{size_bytes / (1024 * 1024):.1f} MB"
    if size_bytes >= 1024:
        return f"{size_bytes / 1024:.0f} KB"
    return f"{size_bytes} B"
